{% set name = "universions" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24b72ce1902d18222c38104520b1396adac4c130e1fb20f8e51ed7c7bfdbf88c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - universions = universions:cli

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - universions
  commands:
    - universions --help

about:
  home: https://github.com/fabiencelier/universions
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Get version of other tools.'
  doc_url: https://universions.readthedocs.io/
  dev_url: https://github.com/fabiencelier/universions

extra:
  recipe-maintainers:
    - fabiencelier
